Github Action code formatting check
Automatically run code formatting during PR check and fail if formatting
is incorrect.

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -42,3 +42,10 @@ jobs:
 
       - name: Check executable
         run: ./build/axisem3d --help
+
+      - name: Indent
+        run: |
+          source $CONDA/etc/profile.d/conda.sh && conda activate axisem3d
+          ./tools/indent.sh
+          # fail if git shows any changes:
+          git diff --exit-code && echo "No changes after indenting." || exit 1
